debug: true
progress:
  type: file
source:
  type: mysql
  host: 192.168.123.205
  port: 3306
  user: root
  password: '123456'
  database: beauty
meilisearch:
  api_url: http://192.168.123.205:7700
  api_key:
sync:
  - table: collection
    index: beauty-collections
    full: true
    fields_mapping:
      id:
      title:
      description:
      category:
  - table: picture
    index: beauty-pictures
    full: true
    fields_mapping:
      id:
      description:
      category:
